version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - UVICORN_CMD="uvicorn api:app --host=0.0.0.0 --port=8000"
    restart: always

